# Generated by Django 3.0.2 on 2020-03-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200312_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
