# Generated by Django 3.0.2 on 2020-03-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_person_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='usertype',
            field=models.CharField(max_length=120),
        ),
    ]
