# Generated by Django 3.0.2 on 2020-03-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200315_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bmi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('height', models.CharField(max_length=128)),
                ('weight', models.CharField(max_length=128)),
                ('bmi', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumeFoodDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('food_name', models.CharField(max_length=128)),
                ('kcal', models.CharField(max_length=128)),
                ('fat', models.CharField(max_length=128)),
                ('protein', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=128)),
                ('kcal', models.CharField(max_length=128)),
                ('fat', models.CharField(max_length=128)),
                ('protein', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
            ],
        ),
    ]
