# Generated by Django 3.0.2 on 2020-03-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bmi_consumefooddetail_fooddetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddetail',
            name='category',
            field=models.CharField(choices=[('snacks', 'snacks'), ('dinner', 'dinner'), ('lunch', 'lunch'), ('breakfast', 'breakfast')], max_length=128),
        ),
    ]
