# Generated by Django 3.0.2 on 2020-03-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200318_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumefooddetail',
            old_name='fat',
            new_name='gram',
        ),
        migrations.RemoveField(
            model_name='consumefooddetail',
            name='kcal',
        ),
        migrations.RemoveField(
            model_name='consumefooddetail',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='fooddetail',
            name='kcal',
        ),
        migrations.AddField(
            model_name='fooddetail',
            name='cal',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='fooddetail',
            name='carbs',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='fooddetail',
            name='category',
            field=models.CharField(choices=[('dinner', 'dinner'), ('snacks', 'snacks'), ('breakfast', 'breakfast'), ('lunch', 'lunch')], default='lunch', max_length=128),
        ),
    ]
