# Generated by Django 3.0.2 on 2020-03-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200318_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profile',
        ),
        migrations.AlterField(
            model_name='fooddetail',
            name='category',
            field=models.CharField(choices=[('dinner', 'dinner'), ('snacks', 'snacks'), ('lunch', 'lunch'), ('breakfast', 'breakfast')], default='lunch', max_length=128),
        ),
    ]
