# Generated by Django 3.0.2 on 2020-03-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200319_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddetail',
            name='category',
            field=models.CharField(choices=[('snacks', 'snacks'), ('dinner', 'dinner'), ('lunch', 'lunch'), ('breakfast', 'breakfast')], default='lunch', max_length=128),
        ),
    ]
