# Generated by Django 3.0.2 on 2020-03-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200320_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumefooddetail',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fooddetail',
            name='category',
            field=models.CharField(choices=[('lunch', 'lunch'), ('breakfast', 'breakfast'), ('dinner', 'dinner'), ('snacks', 'snacks')], default='lunch', max_length=128),
        ),
    ]
