# Generated by Django 3.0.2 on 2020-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200324_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumefooddetail',
            name='category',
            field=models.CharField(choices=[('dinner', 'dinner'), ('lunch', 'lunch'), ('snacks', 'snacks'), ('breakfast', 'breakfast')], default='breakfast', max_length=128),
        ),
        migrations.AlterField(
            model_name='fooddetail',
            name='category',
            field=models.CharField(choices=[('dinner', 'dinner'), ('lunch', 'lunch'), ('snacks', 'snacks'), ('breakfast', 'breakfast')], default='lunch', max_length=128),
        ),
    ]
